name: apars_media_example
description: Example app demonstrating the Apars Media Flutter SDK.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  apars_media:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
